services:
  # FastAPI Application
  daftar_fastapi:
    build:
      context: ..
      dockerfile: Docker/minirag/Dockerfile
    container_name: daftar_fastapi
    ports:
      - "8109:8101"
    volumes:
      - daftar_fastapi_data:/app/Assets
      # Forces downloaded AI models to save on the 2TB drive
      - /srv/mergerfs/2TB/daftar_hf_cache:/app/cache
    networks:
      - daftar_backend
    restart: always
    depends_on:
      daftar_pgvector:
        condition: service_healthy
    env_file:
      - ./env/.env.app
    environment:
      - POSTGRES_HOST=daftar_pgvector
      - POSTGRES_PORT=5432
      - HF_HOME=/app/cache
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ulimits:
      core: 0
    deploy:
      resources:
        limits:
          cpus: '1.0'    # Max 1 CPU core
          memory: 1G     # Max 1GB RAM

  # Frontend Application
  daftar_frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: daftar_frontend
    ports:
      - "5174:80"
    restart: always
    networks:
      - daftar_backend

  # Nginx Service
  daftar_nginx:
    image: nginx:latest
    container_name: daftar_nginx
    ports:
      - "8999:80"
    volumes:
      - ./Nginx/Default.conf:/etc/nginx/conf.d/Default.conf
    depends_on:
      - daftar_fastapi
    networks:
      - daftar_backend
    restart: always

  # PostgreSQL (PGvector)
  daftar_pgvector:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: daftar_pgvector
    ports:
      - "5536:5432"
    volumes:
      # Moved from Docker volume to the 2TB drive
      - /srv/mergerfs/2TB/daftar_db:/var/lib/postgresql/data
    env_file:
      - ./env/.env.postgres
    networks:
      - daftar_backend
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    ulimits:
      core: 0
    deploy:
      resources:
        limits:
          cpus: '0.5'    # Max half a CPU core
          memory: 512M   # Max 512MB RAM

  # Qdrant (Vector DB)
  daftar_qdrant:
    image: qdrant/qdrant:latest
    container_name: daftar_qdrant
    ports:
      - "6337:6333"
      - "6338:6334"
    volumes:
      # Moved from Docker volume to the 2TB drive
      - /srv/mergerfs/2TB/daftar_qdrant:/qdrant/storage
    networks:
      - daftar_backend
    restart: always
    ulimits:
      core: 0
    deploy:
      resources:
        limits:
          cpus: '0.5'    # Max half a CPU core
          memory: 512M   # Max 512MB RAM

networks:
  daftar_backend:
    driver: bridge

volumes:
  daftar_fastapi_data:
  # daftar_pgvector_data and daftar_qdrant_data removed because they are now direct paths on the 2TB drive